version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: contract_user
      POSTGRES_PASSWORD: contract_pass
      POSTGRES_DB: contract_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: contract-backend
    environment:
      DATABASE_URL: postgresql+psycopg2://contract_user:contract_pass@db:5432/contract_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: contract-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      # Можно добавить node_modules, если нужно ускорить npm install:
      # - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  pgdata: